# Generated by Django 5.2.3 on 2025-08-15 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_notif_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('app', 'App'), ('email', 'Email')], default='app', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='notif_frequency',
        ),
        migrations.AddField(
            model_name='customuser',
            name='notif_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.notificationtype'),
            preserve_default=False,
        ),
    ]
