# Generated by Django 5.2.3 on 2025-08-16 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notificationtype_remove_customuser_notif_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='notif_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.notificationtype'),
        ),
    ]
