# Generated by Django 5.2.3 on 2025-08-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_notif_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notif_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('off', 'Off')], default='daily', max_length=10),
        ),
    ]
