# Generated by Django 5.2.3 on 2025-08-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_due',
            field=models.BooleanField(default=False),
        ),
    ]
